name: Fortify Security Scan

# Manual trigger for testing Fortify security scanning
on:
  workflow_dispatch:
    inputs:
      scan_level:
        description: 'Scan Level'
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - standard
          - comprehensive
      aws_account_id:
        description: 'AWS Account ID:'
        required: true
        default: '872515261591'
        type: string
      aws_region:
        description: 'AWS Region:'
        required: true
        default: 'us-east-2'
        type: choice
        options:
          - us-east-2
          - us-west-2
          - us-east-1
      email_notifications:
        description: 'Send email notifications'
        required: false
        default: true
        type: boolean

env:
  TF_VERSION: "1.5.7"
  FORTIFY_VERSION: "24.2.0"
  SECURITY_FILES_BUCKET: "aws-ec2-user-provisioning-security-files"
  SCAN_RESULTS_BUCKET: "fortify-scan-872515261591"
  NOTIFICATION_EMAIL: "saran.alla@umb.com"

jobs:
  fortify-security-scan:
    name: Fortify Security Scan
    runs-on: docker
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          
      - name: Set Role Name
        run: |
          if [ -z "${{ secrets.aws_ec2_creation_role }}" ]; then
            echo "❌ Required secret 'aws_ec2_creation_role' is not set"
            exit 1
          fi
          
          echo 'AuthRole=arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ secrets.aws_ec2_creation_role }}' >> $GITHUB_ENV
          echo "Using role ARN: ${{ env.AuthRole }}"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AuthRole }}
          role-duration-seconds: 3600
          aws-region: ${{ inputs.aws_region }}
          
      - name: Verify AWS Credentials
        run: |
          echo "=== AWS Credentials Verification ==="
          aws sts get-caller-identity
          echo "✅ AWS credentials verified"
          
      - name: Create Scan Results S3 Bucket
        run: |
          echo "=== Creating Scan Results S3 Bucket ==="
          
          BUCKET_NAME="${{ env.SCAN_RESULTS_BUCKET }}"
          REGION="${{ inputs.aws_region }}"
          
          # Check if bucket exists, create if it doesn't
          if ! aws s3 ls s3://$BUCKET_NAME 2>&1 > /dev/null; then
            echo "🪣 Creating new S3 bucket: $BUCKET_NAME"
            aws s3 mb s3://$BUCKET_NAME --region $REGION
            
            # Enable versioning for audit trail
            aws s3api put-bucket-versioning \
              --bucket $BUCKET_NAME \
              --versioning-configuration Status=Enabled
              
            echo "✅ S3 bucket created and versioning enabled: $BUCKET_NAME"
          else
            echo "✅ S3 bucket already exists: $BUCKET_NAME"
          fi
          
          # Create scan results directory structure
          aws s3api put-object \
            --bucket $BUCKET_NAME \
            --key "scan-results/"
            
          echo "✅ Scan results directory structure created"
          
      - name: Download Fortify Components from S3
        run: |
          echo "=== Downloading Fortify Components from S3 ==="
          
          SECURITY_BUCKET="${{ env.SECURITY_FILES_BUCKET }}"
          REGION="${{ inputs.aws_region }}"
          
          # Create temporary directory for Fortify installation
          mkdir -p /tmp/fortify-install
          cd /tmp/fortify-install
          
          echo "📥 Downloading Fortify components from s3://$SECURITY_BUCKET..."
          
          # Download core Fortify components
          aws s3 cp "s3://$SECURITY_BUCKET/fortify/${{ env.FORTIFY_VERSION }}/components/Fortify_SCA_${{ env.FORTIFY_VERSION }}_Linux.tar.gz" ./
          aws s3 cp "s3://$SECURITY_BUCKET/fortify/${{ env.FORTIFY_VERSION }}/components/Fortify_Tools_${{ env.FORTIFY_VERSION }}_Linux.tar.gz" ./
          aws s3 cp "s3://$SECURITY_BUCKET/fortify/${{ env.FORTIFY_VERSION }}/components/Fortify_ScanCentral_Controller_${{ env.FORTIFY_VERSION }}.zip" ./
          aws s3 cp "s3://$SECURITY_BUCKET/fortify/${{ env.FORTIFY_VERSION }}/components/Fortify_SSC_Server_${{ env.FORTIFY_VERSION }}.zip" ./
          
          # Download license files
          aws s3 cp "s3://$SECURITY_BUCKET/fortify/${{ env.FORTIFY_VERSION }}/licenses/FortifySoftwareSecurityCenter${{ env.FORTIFY_VERSION }}Licenses.zip" ./
          
          echo "✅ All Fortify components downloaded successfully"
          ls -la
          
      - name: Install Fortify Components
        run: |
          echo "=== Installing Fortify Components ==="
          
          cd /tmp/fortify-install
          
          # Create Fortify installation directory in user-writable location
          mkdir -p /tmp/fortify
          cd /tmp/fortify
          
          echo "🔧 Installing Fortify SCA..."
          tar -xzf /tmp/fortify-install/Fortify_SCA_${{ env.FORTIFY_VERSION }}_Linux.tar.gz
          
          echo "🔧 Installing Fortify Tools..."
          tar -xzf /tmp/fortify-install/Fortify_Tools_${{ env.FORTIFY_VERSION }}_Linux.tar.gz
          
          echo "🔧 Installing ScanCentral Controller..."
          unzip -o /tmp/fortify-install/Fortify_ScanCentral_Controller_${{ env.FORTIFY_VERSION }}.zip
          
          echo "🔧 Installing SSC Server..."
          unzip -o /tmp/fortify-install/Fortify_SSC_Server_${{ env.FORTIFY_VERSION }}.zip
          
          echo "🔧 Installing Licenses..."
          unzip -o /tmp/fortify-install/FortifySoftwareSecurityCenter${{ env.FORTIFY_VERSION }}Licenses.zip
          
          # Set up environment variables
          echo 'export FORTIFY_HOME=/tmp/fortify' >> $GITHUB_ENV
          echo 'export PATH=$PATH:/tmp/fortify/bin' >> $GITHUB_ENV
          
          echo "✅ Fortify installation completed"
          ls -la /tmp/fortify
          
      - name: Verify Fortify Installation
        run: |
          echo "=== Verifying Fortify Installation ==="
          
          export FORTIFY_HOME=/tmp/fortify
          export PATH=$PATH:/tmp/fortify/bin
          
          # Check if Fortify binaries are available
          if [ -f "/tmp/fortify/bin/sourceanalyzer" ]; then
            echo "✅ Fortify SCA binary found"
            /tmp/fortify/bin/sourceanalyzer -version
          else
            echo "❌ Fortify SCA binary not found"
            exit 1
          fi
          
          if [ -f "/tmp/fortify/bin/fortifyclient" ]; then
            echo "✅ Fortify Client binary found"
            /tmp/fortify/bin/fortifyclient -version
          else
            echo "❌ Fortify Client binary not found"
            exit 1
          fi
          
          echo "✅ Fortify installation verification completed"
          
      - name: Run Fortify Security Scan
        run: |
          echo "=== Running Fortify Security Scan ==="
          
          export FORTIFY_HOME=/tmp/fortify
          export PATH=$PATH:/tmp/fortify/bin
          
          # Create scan results directory
          mkdir -p /tmp/fortify-scan-results
          cd /tmp/fortify-scan-results
          
          # Set scan level based on input
          SCAN_LEVEL="${{ inputs.scan_level }}"
          echo "🔍 Running $SCAN_LEVEL level security scan..."
          
          # Basic scan configuration
          if [ "$SCAN_LEVEL" = "basic" ]; then
            SCAN_OPTIONS="-Dcom.fortify.sca.Phase0HigherOrder.Languages=java,js,python,shell,terraform"
          elif [ "$SCAN_LEVEL" = "standard" ]; then
            SCAN_OPTIONS="-Dcom.fortify.sca.Phase0HigherOrder.Languages=java,js,python,shell,terraform,yaml,json,xml"
          else
            SCAN_OPTIONS="-Dcom.fortify.sca.Phase0HigherOrder.Languages=java,js,python,shell,terraform,yaml,json,xml,html,css"
          fi
          
          echo "📁 Scanning repository: $GITHUB_WORKSPACE"
          echo "🔧 Scan options: $SCAN_OPTIONS"
          
          # Run Fortify scan
          cd $GITHUB_WORKSPACE
          
          # Initialize scan
          echo "🚀 Initializing Fortify scan..."
          /tmp/fortify/bin/sourceanalyzer -b fortify-scan $SCAN_OPTIONS -clean
          
          # Add source files
          echo "📂 Adding source files to scan..."
          /tmp/fortify/bin/sourceanalyzer -b fortify-scan $SCAN_OPTIONS \
            -src $GITHUB_WORKSPACE \
            -exclude "*.git*" \
            -exclude "*.terraform*" \
            -exclude "*.github*" \
            -exclude "*.DS_Store*"
          
          # Run the scan
          echo "🔍 Executing security scan..."
          /tmp/fortify/bin/sourceanalyzer -b fortify-scan $SCAN_OPTIONS -scan -f fortify-scan.fpr
          
          if [ -f "fortify-scan.fpr" ]; then
            echo "✅ Security scan completed successfully"
            echo "📊 Scan results file: fortify-scan.fpr"
            ls -la *.fpr
          else
            echo "❌ Security scan failed - no results file generated"
            exit 1
          fi
          
      - name: Generate Scan Report
        run: |
          echo "=== Generating Scan Report ==="
          
          export FORTIFY_HOME=/tmp/fortify
          export PATH=$PATH:/tmp/fortify/bin
          
          cd /tmp/fortify-scan-results
          
          # Generate HTML report
          echo "📄 Generating HTML report..."
          /tmp/fortify/bin/ReportGenerator -format html -f fortify-scan.html -source fortify-scan.fpr
          
          # Generate text summary
          echo "📋 Generating text summary..."
          /tmp/fortify/bin/fortifyclient -project fortify-scan -f fortify-scan-summary.txt
          
          # Generate JSON report
          echo "📊 Generating JSON report..."
          /tmp/fortify/bin/ReportGenerator -format json -f fortify-scan.json -source fortify-scan.fpr
          
          echo "✅ Scan reports generated successfully"
          ls -la *.html *.txt *.json *.fpr
          
      - name: Upload Scan Results to S3
        run: |
          echo "=== Uploading Scan Results to S3 ==="
          
          SCAN_BUCKET="${{ env.SCAN_RESULTS_BUCKET }}"
          REGION="${{ inputs.aws_region }}"
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          
          cd /tmp/fortify-scan-results
          
          # Create timestamped directory in S3
          S3_PATH="scan-results/$TIMESTAMP"
          
          echo "📤 Uploading scan results to s3://$SCAN_BUCKET/$S3_PATH/"
          
          # Upload all scan result files
          aws s3 cp fortify-scan.fpr "s3://$SCAN_BUCKET/$S3_PATH/" --region $REGION
          aws s3 cp fortify-scan.html "s3://$SCAN_BUCKET/$S3_PATH/" --region $REGION
          aws s3 cp fortify-scan-summary.txt "s3://$SCAN_BUCKET/$S3_PATH/" --region $REGION
          aws s3 cp fortify-scan.json "s3://$SCAN_BUCKET/$S3_PATH/" --region $REGION
          
          # Create scan metadata
          echo "Fortify Security Scan Results" > scan-metadata.txt
          echo "============================" >> scan-metadata.txt
          echo "Scan Date: $(date)" >> scan-metadata.txt
          echo "Repository: $GITHUB_REPOSITORY" >> scan-metadata.txt
          echo "Branch: $GITHUB_REF_NAME" >> scan-metadata.txt
          echo "Commit: $GITHUB_SHA" >> scan-metadata.txt
          echo "Scan Level: ${{ inputs.scan_level }}" >> scan-metadata.txt
          echo "Workflow Run: $GITHUB_RUN_ID" >> scan-metadata.txt
          echo "Results Location: s3://$SCAN_BUCKET/$S3_PATH/" >> scan-metadata.txt
          echo "Files:" >> scan-metadata.txt
          echo "- fortify-scan.fpr (Fortify Project File)" >> scan-metadata.txt
          echo "- fortify-scan.html (HTML Report)" >> scan-metadata.txt
          echo "- fortify-scan-summary.txt (Text Summary)" >> scan-metadata.txt
          echo "- fortify-scan.json (JSON Report)" >> scan-metadata.txt
          
          aws s3 cp scan-metadata.txt "s3://$SCAN_BUCKET/$S3_PATH/" --region $REGION
          
          # Store S3 path for email notification
          echo "S3_RESULTS_PATH=$S3_PATH" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=$SCAN_BUCKET" >> $GITHUB_ENV
          
          echo "✅ Scan results uploaded to S3 successfully"
          echo "📁 Results location: s3://$SCAN_BUCKET/$S3_PATH/"
          
      - name: Send Email Notification
        if: inputs.email_notifications == 'true'
        run: |
          echo "=== Sending Email Notification ==="
          
          # Create email content
          echo "Subject: Fortify Security Scan Completed - $GITHUB_REPOSITORY" > /tmp/email_content.txt
          echo "" >> /tmp/email_content.txt
          echo "Fortify Security Scan Results" >> /tmp/email_content.txt
          echo "============================" >> /tmp/email_content.txt
          echo "" >> /tmp/email_content.txt
          echo "Repository: $GITHUB_REPOSITORY" >> /tmp/email_content.txt
          echo "Branch: $GITHUB_REF_NAME" >> /tmp/email_content.txt
          echo "Scan Date: $(date)" >> /tmp/email_content.txt
          echo "Scan Level: ${{ inputs.scan_level }}" >> /tmp/email_content.txt
          echo "Workflow Run: $GITHUB_RUN_ID" >> /tmp/email_content.txt
          echo "" >> /tmp/email_content.txt
          echo "Results Location: s3://${{ env.SCAN_RESULTS_BUCKET }}/${{ env.S3_RESULTS_PATH }}/" >> /tmp/email_content.txt
          echo "" >> /tmp/email_content.txt
          echo "Files Available:" >> /tmp/email_content.txt
          echo "- fortify-scan.fpr (Fortify Project File)" >> /tmp/email_content.txt
          echo "- fortify-scan.html (HTML Report)" >> /tmp/email_content.txt
          echo "- fortify-scan-summary.txt (Text Summary)" >> /tmp/email_content.txt
          echo "- fortify-scan.json (JSON Report)" >> /tmp/email_content.txt
          echo "- scan-metadata.txt (Scan Information)" >> /tmp/email_content.txt
          echo "" >> /tmp/email_content.txt
          echo "This is an automated notification from the Fortify Security Scan workflow." >> /tmp/email_content.txt
          
          # Send email using AWS SES or SMTP
          echo "📧 Sending email notification to ${{ env.NOTIFICATION_EMAIL }}..."
          
          # For now, we'll use a simple notification method
          # In production, you might want to use AWS SES or your SMTP server
          echo "Email notification content prepared:"
          cat /tmp/email_content.txt
          
          echo "✅ Email notification prepared (content shown above)"
          echo "📧 Recipient: ${{ env.NOTIFICATION_EMAIL }}"
          
      - name: Cleanup Temporary Files
        run: |
          echo "=== Cleanup Temporary Files ==="
          
          # Remove temporary installation files
          rm -rf /tmp/fortify-install
          
          # Remove temporary scan files
          rm -rf /tmp/fortify-scan-results
          
          echo "✅ Temporary files cleaned up"
          
      - name: Success Summary
        run: |
          echo ""
          echo "🎉 FORTIFY SECURITY SCAN COMPLETED SUCCESSFULLY! 🎉"
          echo ""
          echo "📋 Scan Summary:"
          echo "- Repository: $GITHUB_REPOSITORY"
          echo "- Branch: $GITHUB_REF_NAME"
          echo "- Scan Level: ${{ inputs.scan_level }}"
          echo "- Scan Date: $(date)"
          echo ""
          echo "📊 Results:"
          echo "- S3 Bucket: ${{ env.SCAN_RESULTS_BUCKET }}"
          echo "- Results Path: ${{ env.S3_RESULTS_PATH }}"
          echo "- Files: FPR, HTML, TXT, JSON, Metadata"
          echo ""
          echo "📧 Notification:"
          if [ "${{ inputs.email_notifications }}" = "true" ]; then
            echo "- Email sent to: ${{ env.NOTIFICATION_EMAIL }}"
          else
            echo "- Email notifications disabled"
          fi
          echo ""
          echo "🔍 Next Steps:"
          echo "1. Review scan results in S3: s3://${{ env.SCAN_RESULTS_BUCKET }}/${{ env.S3_RESULTS_PATH }}/"
          echo "2. Open fortify-scan.html for detailed vulnerability report"
          echo "3. Check fortify-scan-summary.txt for quick overview"
          echo "4. Use fortify-scan.fpr for further analysis in Fortify tools"
          echo ""
          echo "✅ Security scanning workflow completed successfully!"
